# Generated by Django 3.1.2 on 2020-11-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201102_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=64)),
                ('winner', models.CharField(max_length=64)),
                ('listing_id', models.IntegerField()),
                ('win_bid', models.IntegerField()),
            ],
        ),
    ]
